#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
#Answer: 4613732

require './002_even_fibonacci_sum'


describe Processor do
  before(:all) do 
    @processor = Processor.new
  end

  describe "#sum" do
    it "returns the correct answer" do
      sequence = @processor.generate_sequence([1,2], 4000000)
      @processor.sum(sequence).should == 4613732
    end
  end

  describe "#generate_sequence" do

    it "returns nil if starting sequence has less than two elements" do
      @processor.generate_sequence([1], 100).should == nil
    end

    it "returns a correct sequence" do
      expected = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
      result = @processor.generate_sequence([1,2], 89)
      (0...10).each do |i|
        result[i].should == expected[i]
      end
    end
  end

end
